### PR TITLE
Fix calcs

### PR DESCRIPTION
**Pull request by MichaelCurrin**
Here's the problem.
Screen Shot 2021-06-30 at 5 33 05 pm

The tip amount was almost double the taxes amount. So I updated that.

The person cal was multiplying instead of dividing - so more people made a _higher_ cost per person.

Also made the calcs _much_ simpler using `value * (1 + rate)` instead of `value + value * rate`

### CODE REVIEW

**Comment by beatrizsmerino** [comment]
Thank you very much, I will see it later

**Comment by MichaelCurrin** [comment]
Thanks. BTW I didn't update the calcs on the column on the right though.

**Comment by MichaelCurrin** [comment]
Here is the fixed view.

Also I moved `.toFixed` to the index page.  The JS should be dealing with only numbers without formatting it. Formatting of numbers should handled by the HTML view _just_ as the number is displayed.

Screen Shot 2021-07-01 at 2 56 23 pm

Screen Shot 2021-07-01 at 2 56 19 pm

**Comment by MichaelCurrin** [comment]
You should also update your screenshot used in README.md to show the fixed accurate values

**Pull request merged**
